project:
  type: website
  output-dir: docs

from: markdown+emoji

website:
  title: "Wei Jing Ang"
  page-navigation: true
  
  sidebar:
    # - id: projects
    #   title: "Projects"
    #   style: "floating"
    #   align: left
    #   contents:
    #     - text: "Projects"
    #       href: projects/index.qmd
    #     - text: "Amazon"
    #       href: projects/Amazon/index.qmd
    #     - text: "Lakes"
    #       href: projects/Lakes/index.qmd
    #     - text: "Mekong"
    #       href: projects/Mekong/index.qmd

    - id: collection
      contents:
        - text: "Collection"
          href: collection/index.qmd
        - text: "Designs" 
          href: collection/designs.qmd
        - text: "Photographs"
          href: collection/photographs.qmd
        - text: "Rocks"
          href: collection/rocks.qmd

  navbar:
    title: false
    background: light
    foreground: dark
    left:
      - text: '<i class="fa fa-home fa-xl" style="color:#E6A1A8;"></i></a>'
        href: index.html
    right:
      - text: "Visualisation"
        href: projects/visualisation/visualisation.qmd
      - text: "Analysis"
        href: projects/analysis/analysis.qmd
      - text: "Research"
        href: projects/research/research.qmd
        
  page-footer:
    right: "This page is built with {{< fa heart >}} and [Quarto](https://quarto.org/)."
    left: "Wei Jing Ang"

format: 
  html:
    theme: 
    - sandstone
    - custom.scss
    
execute:
  freeze: auto
    
# Design tips:
# 1. maggieappleton.com
